### ISSUE TITLE
Build not triggered by npm run watch

### ISSUE THREAD

**Issue by bastihilger** [stidges/laravel-mix-mjml#1]
First of all: Thank you for this plugin! I am proud to give it its first star.

I'm not sure if this can be implemented on your side at all, but is there a way to trigger the build when  `npm run watch` is running? It does not seem to work so far (my mix version is 2.1.14). When I change something in an mjml file, nothing happens. 

Cheers, Sebastian

**Comment by stidges** [comment]
Thank you for reporting this! I have just pushed a new version that should fix this issue. Please let me know if it works for you :)

**Comment by bastihilger** [comment]
Hey there - thanks for this. I will as soon a I use it in a project again (I removed it from the last project - not because it was not working, but it was a bit of overkill for that project and in the end I opted for plain text mails).

**Comment by martinstefek** [comment]
Hello, the watch isn't working for me even with your new version that was supposed to fix this issue.
My laravel-mix version is 2.1.14
