### ISSUE TITLE
Never stop compiling when using with watch

### ISSUE THREAD

**Issue by potsky** [stidges/laravel-mix-mjml#11]
Hello,

firstofall, thank you for this package 👍 

When running `npm run watch`, first time it compiles the code, everything is ok.
But as soon as I change a `.mjml`, `.js` or `.css` file, it never stop compiling and the CPU is hot ♨️ 

Here is the `package.json` :

```json
"devDependencies": {
    "@tailwindcss/forms": "^0.4.0",
    "@tailwindcss/typography": "^0.5.0",
    "alpinejs": "^3.8.0",
    "autoprefixer": "^10.4.2",
    "axios": "^0.21",
    "laravel-mix": "^6.0",
    "laravel-mix-mjml": "^4.0.0",
    "lodash": "^4.17.19",
    "postcss": "^8.4.5",
    "postcss-import": "^14.0",
    "prettier": "2.4.1",
    "tailwindcss": "^3.0.11"
}
```

and here is the `webpack.mix.js` file (with postCss for Tailwind 3.x):

```js
const mix = require('laravel-mix');
require('laravel-mix-mjml');

mix.js('resources/js/app.js', 'public/js')
    .postCss('resources/css/app.css', 'public/css', [
            require('postcss-import'),
            require('tailwindcss'),
            require('autoprefixer')
        ]
    )
    .mjml();

if (mix.inProduction()) {
    mix.version();
}
```

If I remove the call to `.mjml();` in the mix file, the problem does not occur when editing`.js`, `.css` and of course `.mjml` files.

Any idea ?

**Comment by potsky** [comment]
Hello,

this is not really a problem of the package but of the way *mix* handles *watch* with other tools like *tailwindcss*.
Given that the mjml file is generated in the `views/mail` directory, mix then checks the `mjml-example.blade.file` and it seems to loop with the package.

The solution I have found is to move the generated mjml file in another view directory and to add this directory in `config/view.php`

**Comment by brizzo** [comment]
Just came across this. Adding `'!./resources/views/mail/**/*.blade.php'` to the content array in tailwind.config.js solves the issue.

```
module.exports = {
    content: [
        './resources/views/**/*.blade.php',
        '!./resources/views/mail/**/*.blade.php',
    ],
    ...
}
```
This prevents Tailwind from recompiling views in this folder.
