### ISSUE TITLE
Output path does not works on windows 

### ISSUE THREAD

**Issue by dayio** [stidges/laravel-mix-mjml#8]
Hi ! 

Thanks for you library, 

I've upgraded to the version 3.0.0 and i noticed that my compiled files are copied inside the same directory where the original mjml files are stored

I found out that on line 83 of index.js there is forward slashes, those are the cause of the issue

`.replace(`${options.sourceRoot}/`, `${output.relativePath()}/`)`

I think removing those will not impact builds on posix systems, since this is a string replace of a previously builded File object where the path is normalized with `normalizedOutputPath`.

the command i use is `mix.mjml('resources/emails', 'resources/views/emails');`

With the trailing slashes in the replace function i get this: 

```
resources\emails\system\warehouse-order.mjml
resources\emails 
resources\views\emails 
resources\emails\system\warehouse-order.blade.php
```

And without the slashes: 

```
file: resources\emails\system\warehouse-order.mjml
resources\emails
resources\views\emails 
resources\views\emails\system\warehouse-order.blade.php
```

I'll make a PR, could you take a look ? 

Thanks and have a nice day :) !

**Comment by stidges** [comment]
Thanks again for this! I've just released v4.0.0 to include your PR :)
